name: Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    name: Deploy bundle
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: databricks/setup-cli@main
      - name: Deploy bundle
        run: databricks bundle deploy
        env:
          DATABRICKS_AUTH_TYPE: github-oidc
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_BUNDLE_ENV: prod
